import {
  attribute,
  autoGeneratedHashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";

@table("document_table")
export class Document {
  @autoGeneratedHashKey()
  id: string;

  /**
   * Document's User ID
   */
  @attribute({ type: "String" })
  userId?: string;

  /**
   * Document Name
   */
  @attribute({ type: "String" })
  name?: string;

  /**
   * Document's template ID
   */
  @attribute({ type: "String" })
  templateId?: string;

  /**
   * Document's creation date
   */
  @attribute({
    type: "Date",
    defaultProvider: () => new Date(),
  })
  createdAt?: Date;
}
