export enum errorDomain {
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORIZED = "UNAUTHORIZED",
  CREATION_ERROR = "CREATION_ERROR",
  TOKEN_VERIFICATION_ERROR = "TOKEN_VERIFICATION_ERROR",
  TOKEN_GENERATION_ERROR = "TOKEN_GENERATION_ERROR",
  FORBIDDEN = "FORBIDDEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  UNKNOWN = "UNKNOWN",
}
